import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import preferencesRouter from "./preferences";
import meetingRequestsRouter from "./meetingRequests";
import conversationsRouter from "./conversations";
import teamChannelsRouter from "./teamChannels";
import amazonAlertsRouter from "./amazonAlerts";
import dashboardRouter from "./dashboard";
import openaiRouter from "./openai";
import soulRouter from "./soul";
import brainRouter from "./brain";
import channelsRouter from "./channels";
import webhooksRouter from "./webhooks";
import voiceRouter from "./voice";
import microsoftRouter from "./microsoft";
import humeRouter from "./hume";
import voiceLogRouter from "./voice-log";
import bossMemoryRouter from "./bossMemory";
import brainTeamsRouter from "./brain-teams";
import brainTelegramRouter from "./brain-telegram";
import customersRouter from "./customers";
import elevenLabsRouter from "./elevenlabs";
import voiceNoteTestRouter from "./voice-note-test";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(preferencesRouter);
router.use(meetingRequestsRouter);
router.use(conversationsRouter);
router.use(teamChannelsRouter);
router.use(amazonAlertsRouter);
router.use(dashboardRouter);
router.use(openaiRouter);
router.use(soulRouter);
router.use(brainRouter);
router.use(channelsRouter);
router.use(webhooksRouter);
router.use(voiceRouter);
router.use(microsoftRouter);
router.use(humeRouter);
router.use(voiceLogRouter);
router.use(bossMemoryRouter);
router.use(brainTeamsRouter);
router.use(brainTelegramRouter);
router.use(customersRouter);
router.use(elevenLabsRouter);
router.use(voiceNoteTestRouter);

export default router;
